<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 What is exploratory data analysis? | Exploratory Data Analysis in the 21st Century</title>
  <meta name="description" content="This is a book about EDA today." />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 What is exploratory data analysis? | Exploratory Data Analysis in the 21st Century" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a book about EDA today." />
  <meta name="github-repo" content="https://github.com/dicook/explore-data" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 What is exploratory data analysis? | Exploratory Data Analysis in the 21st Century" />
  
  <meta name="twitter:description" content="This is a book about EDA today." />
  

<meta name="author" content="Di Cook and Emi Tanaka" />


<meta name="date" content="2023-08-30" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="initial-data-analysis.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="libs/viz-1.8.2/viz.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/grViz-binding-1.0.10/grViz.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">This is a book about EDA today. </a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a></li>
<li class="chapter" data-level="2" data-path="what-is-eda.html"><a href="what-is-eda.html"><i class="fa fa-check"></i><b>2</b> What is exploratory data analysis?</a>
<ul>
<li class="chapter" data-level="2.1" data-path="what-is-eda.html"><a href="what-is-eda.html#common-descriptions"><i class="fa fa-check"></i><b>2.1</b> Common descriptions</a></li>
<li class="chapter" data-level="2.2" data-path="what-is-eda.html"><a href="what-is-eda.html#components-of-data-analysis"><i class="fa fa-check"></i><b>2.2</b> Components of data analysis</a></li>
<li class="chapter" data-level="2.3" data-path="what-is-eda.html"><a href="what-is-eda.html#differentiating-eda-from-cda"><i class="fa fa-check"></i><b>2.3</b> Differentiating EDA from CDA</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="what-is-eda.html"><a href="what-is-eda.html#from-the-case-study"><i class="fa fa-check"></i><b>2.3.1</b> From the case study</a></li>
<li class="chapter" data-level="2.3.2" data-path="what-is-eda.html"><a href="what-is-eda.html#eda-approach"><i class="fa fa-check"></i><b>2.3.2</b> EDA approach</a></li>
<li class="chapter" data-level="2.3.3" data-path="what-is-eda.html"><a href="what-is-eda.html#what-we-learned-from-eda"><i class="fa fa-check"></i><b>2.3.3</b> What we learned from EDA</a></li>
<li class="chapter" data-level="2.3.4" data-path="what-is-eda.html"><a href="what-is-eda.html#reality-check"><i class="fa fa-check"></i><b>2.3.4</b> Reality check</a></li>
<li class="chapter" data-level="2.3.5" data-path="what-is-eda.html"><a href="what-is-eda.html#what-is-eda-1"><i class="fa fa-check"></i><b>2.3.5</b> What is EDA?</a></li>
<li class="chapter" data-level="2.3.6" data-path="what-is-eda.html"><a href="what-is-eda.html#isnt-it-data-snooping"><i class="fa fa-check"></i><b>2.3.6</b> Isn’t it data snooping?</a></li>
<li class="chapter" data-level="2.3.7" data-path="what-is-eda.html"><a href="what-is-eda.html#why-arent-there-more-resources-on-eda"><i class="fa fa-check"></i><b>2.3.7</b> Why aren’t there more resources on EDA?</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="what-is-eda.html"><a href="what-is-eda.html#the-origins-of-eda"><i class="fa fa-check"></i><b>2.4</b> The origins of EDA</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="what-is-eda.html"><a href="what-is-eda.html#example-1-stem-and-leaf"><i class="fa fa-check"></i><b>2.4.1</b> Example 1: Stem-and-leaf</a></li>
<li class="chapter" data-level="2.4.2" data-path="what-is-eda.html"><a href="what-is-eda.html#example-1-making-tallies"><i class="fa fa-check"></i><b>2.4.2</b> Example 1: Making tallies</a></li>
<li class="chapter" data-level="2.4.3" data-path="what-is-eda.html"><a href="what-is-eda.html#example-3-boxplots"><i class="fa fa-check"></i><b>2.4.3</b> Example 3: Boxplots</a></li>
<li class="chapter" data-level="2.4.4" data-path="what-is-eda.html"><a href="what-is-eda.html#example-4-easy-re-expression"><i class="fa fa-check"></i><b>2.4.4</b> Example 4: Easy re-expression</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="what-is-eda.html"><a href="what-is-eda.html#exercises"><i class="fa fa-check"></i><b>2.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="initial-data-analysis.html"><a href="initial-data-analysis.html"><i class="fa fa-check"></i><b>3</b> Initial Data Analysis</a>
<ul>
<li class="chapter" data-level="3.1" data-path="initial-data-analysis.html"><a href="initial-data-analysis.html#data-description"><i class="fa fa-check"></i><b>3.1</b> Data description</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="initial-data-analysis.html"><a href="initial-data-analysis.html#checking-the-data-type"><i class="fa fa-check"></i><b>3.1.1</b> Checking the data type</a></li>
<li class="chapter" data-level="3.1.2" data-path="initial-data-analysis.html"><a href="initial-data-analysis.html#checking-the-data-quality"><i class="fa fa-check"></i><b>3.1.2</b> Checking the data quality</a></li>
<li class="chapter" data-level="3.1.3" data-path="initial-data-analysis.html"><a href="initial-data-analysis.html#check-on-data-collection-method"><i class="fa fa-check"></i><b>3.1.3</b> Check on data collection method</a></li>
<li class="chapter" data-level="3.1.4" data-path="initial-data-analysis.html"><a href="initial-data-analysis.html#check-for-experimental-data"><i class="fa fa-check"></i><b>3.1.4</b> Check for experimental data</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="initial-data-analysis.html"><a href="initial-data-analysis.html#model-formulation"><i class="fa fa-check"></i><b>3.2</b> Model formulation</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="initial-data-analysis.html"><a href="initial-data-analysis.html#review-linear-models-in-r"><i class="fa fa-check"></i><b>3.2.1</b> Review: Linear models in R</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="initial-data-analysis.html"><a href="initial-data-analysis.html#model-formulation-1"><i class="fa fa-check"></i><b>3.3</b> Model formulation</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="initial-data-analysis.html"><a href="initial-data-analysis.html#experimental-design"><i class="fa fa-check"></i><b>3.3.1</b> Experimental Design</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="initial-data-analysis.html"><a href="initial-data-analysis.html#summary"><i class="fa fa-check"></i><b>3.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html"><i class="fa fa-check"></i><b>4</b> Working with a single variable</a>
<ul>
<li class="chapter" data-level="4.1" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#possible-features-of-continuous-variables"><i class="fa fa-check"></i><b>4.1</b> Possible features of continuous variables</a></li>
<li class="chapter" data-level="4.2" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#numerical-features-of-a-single-continuous-variables"><i class="fa fa-check"></i><b>4.2</b> Numerical features of a single continuous variables</a></li>
<li class="chapter" data-level="4.3" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#outliers"><i class="fa fa-check"></i><b>4.3</b> Outliers</a></li>
<li class="chapter" data-level="4.4" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#closer-look-at-the-boxplot"><i class="fa fa-check"></i><b>4.4</b> Closer look at the <em>boxplot</em></a></li>
<li class="chapter" data-level="4.5" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#robust-statistics-measure-of-central-tendency"><i class="fa fa-check"></i><b>4.5</b> Robust statistics: measure of central tendency</a></li>
<li class="chapter" data-level="4.6" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#robust-statistics-measure-of-dispersion"><i class="fa fa-check"></i><b>4.6</b> Robust statistics: measure of dispersion</a></li>
<li class="chapter" data-level="4.7" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#transformations"><i class="fa fa-check"></i><b>4.7</b> Transformations</a></li>
<li class="chapter" data-level="4.8" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#categorical-variables"><i class="fa fa-check"></i><b>4.8</b> Categorical variables</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#categorical-factors-un-r"><i class="fa fa-check"></i><b>4.8.1</b> Categorical factors un R</a></li>
<li class="chapter" data-level="4.8.2" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#numerical-factors-in-r"><i class="fa fa-check"></i><b>4.8.2</b> Numerical factors in R</a></li>
<li class="chapter" data-level="4.8.3" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#example-german-bundestag-election-2009"><i class="fa fa-check"></i><b>4.8.3</b> Example: German Bundestag Election 2009</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#order-nominal-variables-meaningfully"><i class="fa fa-check"></i><b>4.9</b> Order nominal variables meaningfully</a></li>
<li class="chapter" data-level="4.10" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#example-aspirin-use-after-heart-attack"><i class="fa fa-check"></i><b>4.10</b> Example: Aspirin use after heart attack</a></li>
<li class="chapter" data-level="4.11" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#consider-combining-factor-levels-with-low-frequencies"><i class="fa fa-check"></i><b>4.11</b> Consider combining factor levels with low frequencies</a></li>
<li class="chapter" data-level="4.12" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#anorexia"><i class="fa fa-check"></i><b>4.12</b> Anorexia</a></li>
<li class="chapter" data-level="4.13" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#titanic"><i class="fa fa-check"></i><b>4.13</b> Titanic</a></li>
<li class="chapter" data-level="4.14" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#coloring-bars"><i class="fa fa-check"></i><b>4.14</b> Coloring bars</a></li>
<li class="chapter" data-level="4.15" data-path="working-with-a-single-variable.html"><a href="working-with-a-single-variable.html#opinion-poll-in-ireland-aug-2013"><i class="fa fa-check"></i><b>4.15</b> Opinion poll in Ireland Aug 2013</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html"><i class="fa fa-check"></i><b>5</b> Bivariate dependencies and relationships</a>
<ul>
<li class="chapter" data-level="5.1" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#motivation"><i class="fa fa-check"></i><b>5.1</b> Motivation</a></li>
<li class="chapter" data-level="5.2" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#the-humble-scatterplot"><i class="fa fa-check"></i><b>5.2</b> The humble scatterplot</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#history"><i class="fa fa-check"></i><b>5.2.1</b> History</a></li>
<li class="chapter" data-level="5.2.2" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#language-and-terminology"><i class="fa fa-check"></i><b>5.2.2</b> Language and terminology</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#common-features-and-their-names"><i class="fa fa-check"></i><b>5.3</b> Common features and their names</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#anscombes-quartet"><i class="fa fa-check"></i><b>5.3.1</b> Anscombe’s quartet</a></li>
<li class="chapter" data-level="5.3.2" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#datasaurus-dozen"><i class="fa fa-check"></i><b>5.3.2</b> DatasauRus dozen</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#case-study-1-olympics"><i class="fa fa-check"></i><b>5.4</b> Case study 1: olympics</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#how-many-athletes-in-the-different-sports"><i class="fa fa-check"></i><b>5.4.1</b> How many athletes in the different sports?</a></li>
<li class="chapter" data-level="5.4.2" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#consolidate-factor-levels"><i class="fa fa-check"></i><b>5.4.2</b> Consolidate factor levels</a></li>
<li class="chapter" data-level="5.4.3" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#split-by-sport"><i class="fa fa-check"></i><b>5.4.3</b> Split by sport</a></li>
<li class="chapter" data-level="5.4.4" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#remove-missings-add-colour-for-sex"><i class="fa fa-check"></i><b>5.4.4</b> Remove missings, add colour for sex</a></li>
<li class="chapter" data-level="5.4.5" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#comparing-association"><i class="fa fa-check"></i><b>5.4.5</b> Comparing association</a></li>
<li class="chapter" data-level="5.4.6" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#comparing-variability"><i class="fa fa-check"></i><b>5.4.6</b> Comparing variability</a></li>
<li class="chapter" data-level="5.4.7" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#summary-1"><i class="fa fa-check"></i><b>5.4.7</b> Summary</a></li>
<li class="chapter" data-level="5.4.8" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#scatterplot-modifications-and-purpose"><i class="fa fa-check"></i><b>5.4.8</b> Scatterplot modifications and purpose</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#numerical-measures-of-association"><i class="fa fa-check"></i><b>5.5</b> Numerical measures of association</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#correlation"><i class="fa fa-check"></i><b>5.5.1</b> Correlation</a></li>
<li class="chapter" data-level="5.5.2" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#peceiving-correlation"><i class="fa fa-check"></i><b>5.5.2</b> Peceiving correlation</a></li>
<li class="chapter" data-level="5.5.3" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#robust-correlation-measures"><i class="fa fa-check"></i><b>5.5.3</b> Robust correlation measures</a></li>
<li class="chapter" data-level="5.5.4" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#robust-correlation-measures-1"><i class="fa fa-check"></i><b>5.5.4</b> Robust correlation measures</a></li>
<li class="chapter" data-level="5.5.5" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#comparison-of-correlation-measures"><i class="fa fa-check"></i><b>5.5.5</b> Comparison of correlation measures</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#case-study-2-movies"><i class="fa fa-check"></i><b>5.6</b> Case study 2: movies</a></li>
<li class="chapter" data-level="5.7" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#case-study-3-cars"><i class="fa fa-check"></i><b>5.7</b> Case study 3: cars</a></li>
<li class="chapter" data-level="5.8" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#circle-of-transformations-for-linearising"><i class="fa fa-check"></i><b>5.8</b> Circle of transformations for linearising</a></li>
<li class="chapter" data-level="5.9" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#case-study-4-soils"><i class="fa fa-check"></i><b>5.9</b> Case study 4: soils</a></li>
<li class="chapter" data-level="5.10" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#case-study-5-covid"><i class="fa fa-check"></i><b>5.10</b> Case study 5: COVID</a></li>
<li class="chapter" data-level="5.11" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#beyond-quantitative-variables"><i class="fa fa-check"></i><b>5.11</b> Beyond quantitative variables</a></li>
<li class="chapter" data-level="5.12" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#simpsons-paradox"><i class="fa fa-check"></i><b>5.12</b> Simpsons paradox</a></li>
<li class="chapter" data-level="5.13" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#spurious-association"><i class="fa fa-check"></i><b>5.13</b> Spurious association</a></li>
<li class="chapter" data-level="5.14" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#checking-association-with-permutations"><i class="fa fa-check"></i><b>5.14</b> Checking association with permutations</a></li>
<li class="chapter" data-level="5.15" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#resources"><i class="fa fa-check"></i><b>5.15</b> Resources</a></li>
<li class="chapter" data-level="5.16" data-path="bivariate-dependencies-and-relationships.html"><a href="bivariate-dependencies-and-relationships.html#exercises-1"><i class="fa fa-check"></i><b>5.16</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="going-beyond-two-variables.html"><a href="going-beyond-two-variables.html"><i class="fa fa-check"></i><b>6</b> Going beyond two variables</a></li>
<li class="chapter" data-level="7" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html"><i class="fa fa-check"></i><b>7</b> Making comparisons between groups and strata</a>
<ul>
<li class="chapter" data-level="7.1" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#pest-resistance-maize"><i class="fa fa-check"></i><b>7.1</b> Pest resistance maize</a></li>
<li class="chapter" data-level="7.2" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#maize-kernels"><i class="fa fa-check"></i><b>7.2</b> Maize kernels</a></li>
<li class="chapter" data-level="7.3" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#comparing-like-with-like"><i class="fa fa-check"></i><b>7.3</b> Comparing like-with-like</a></li>
<li class="chapter" data-level="7.4" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#multi-environment-soybean-trial"><i class="fa fa-check"></i><b>7.4</b> Multi-environment soybean trial</a></li>
<li class="chapter" data-level="7.5" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#types-of-comparison"><i class="fa fa-check"></i><b>7.5</b> Types of comparison</a></li>
<li class="chapter" data-level="7.6" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#weight-of-calves-with-different-diets"><i class="fa fa-check"></i><b>7.6</b> Weight of calves with different diets</a></li>
<li class="chapter" data-level="7.7" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#swiss-bank-notes"><i class="fa fa-check"></i><b>7.7</b> Swiss bank notes</a></li>
<li class="chapter" data-level="7.8" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#comparing-graphically"><i class="fa fa-check"></i><b>7.8</b> Comparing graphically</a></li>
<li class="chapter" data-level="7.9" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#barley-yield"><i class="fa fa-check"></i><b>7.9</b> Barley Yield</a></li>
<li class="chapter" data-level="7.10" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#olive-oils"><i class="fa fa-check"></i><b>7.10</b> Olive oils</a></li>
<li class="chapter" data-level="7.11" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#england-and-east-indies-trade-data"><i class="fa fa-check"></i><b>7.11</b> England and East Indies trade data</a></li>
<li class="chapter" data-level="7.12" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#melbournes-daily-maximum-temperature"><i class="fa fa-check"></i><b>7.12</b> Melbourne’s daily maximum temperature</a></li>
<li class="chapter" data-level="7.13" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#modelling-and-testing-for-comparisons"><i class="fa fa-check"></i><b>7.13</b> Modelling and testing for comparisons</a></li>
<li class="chapter" data-level="7.14" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#pest-resistance-maize-1"><i class="fa fa-check"></i><b>7.14</b> Pest resistance maize</a></li>
<li class="chapter" data-level="7.15" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#two-sample-parametric-tests-t-test"><i class="fa fa-check"></i><b>7.15</b> Two-sample parametric tests: <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="7.16" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#confidence-interval-for-two-sample-difference"><i class="fa fa-check"></i><b>7.16</b> Confidence interval for two sample difference</a></li>
<li class="chapter" data-level="7.17" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#two-sample-non-parametric-tests"><i class="fa fa-check"></i><b>7.17</b> Two sample non-parametric tests</a>
<ul>
<li class="chapter" data-level="7.17.1" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#wilcoxon-rank-sum-test"><i class="fa fa-check"></i><b>7.17.1</b> Wilcoxon rank-sum test</a></li>
</ul></li>
<li class="chapter" data-level="7.18" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#weight-gain-of-calves"><i class="fa fa-check"></i><b>7.18</b> Weight gain of calves</a>
<ul>
<li class="chapter" data-level="7.18.1" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#weight-gain-of-calves-1"><i class="fa fa-check"></i><b>7.18.1</b> Weight gain of calves</a></li>
</ul></li>
<li class="chapter" data-level="7.19" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#soil-nitrogen"><i class="fa fa-check"></i><b>7.19</b> Soil nitrogen</a></li>
<li class="chapter" data-level="7.20" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#controlling-the-family-wise-error-rate"><i class="fa fa-check"></i><b>7.20</b> Controlling the family-wise error rate</a></li>
<li class="chapter" data-level="7.21" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#unadjusted"><i class="fa fa-check"></i><b>7.21</b> Unadjusted</a></li>
<li class="chapter" data-level="7.22" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#bonferonni-adjustment"><i class="fa fa-check"></i><b>7.22</b> Bonferonni adjustment</a></li>
<li class="chapter" data-level="7.23" data-path="making-comparisons-between-groups-and-strata.html"><a href="making-comparisons-between-groups-and-strata.html#mystery-data"><i class="fa fa-check"></i><b>7.23</b> Mystery data</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html"><i class="fa fa-check"></i><b>8</b> Sculpting data using models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#parametric-regression"><i class="fa fa-check"></i><b>8.1</b> Parametric regression</a></li>
<li class="chapter" data-level="8.2" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#example"><i class="fa fa-check"></i><b>8.2</b> Example</a></li>
<li class="chapter" data-level="8.3" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#simulating-data-from-parametric-models"><i class="fa fa-check"></i><b>8.3</b> Simulating data from parametric models</a></li>
<li class="chapter" data-level="8.4" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#logistic-regression"><i class="fa fa-check"></i><b>8.4</b> Logistic regression</a></li>
<li class="chapter" data-level="8.5" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#menarche"><i class="fa fa-check"></i><b>8.5</b> Menarche</a></li>
<li class="chapter" data-level="8.6" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#simulating-data-from-logistic-regression"><i class="fa fa-check"></i><b>8.6</b> Simulating data from logistic regression</a></li>
<li class="chapter" data-level="8.7" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#diagnostics-for-logistic-regression-models"><i class="fa fa-check"></i><b>8.7</b> Diagnostics for logistic regression models</a></li>
<li class="chapter" data-level="8.8" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#diagnostics-for-linear-models"><i class="fa fa-check"></i><b>8.8</b> Diagnostics for linear models</a></li>
<li class="chapter" data-level="8.9" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#assessing-a1-eepsilon_i-0-for-i1ldotsn"><i class="fa fa-check"></i><b>8.9</b> Assessing (A1) <span class="math inline">\(E(\epsilon_i) = 0\)</span> for <span class="math inline">\(i=1,\ldots,n\)</span></a></li>
<li class="chapter" data-level="8.10" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#assessing-a2-a3"><i class="fa fa-check"></i><b>8.10</b> Assessing (A2)-(A3)</a>
<ul>
<li class="chapter" data-level="8.10.1" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#in-r"><i class="fa fa-check"></i><b>8.10.1</b> In R</a></li>
</ul></li>
<li class="chapter" data-level="8.11" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#examining-the-simulated-data-further"><i class="fa fa-check"></i><b>8.11</b> Examining the simulated data further</a></li>
<li class="chapter" data-level="8.12" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#revisiting-outliers"><i class="fa fa-check"></i><b>8.12</b> Revisiting outliers</a></li>
<li class="chapter" data-level="8.13" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#pop-quiz"><i class="fa fa-check"></i><b>8.13</b> Pop Quiz</a></li>
<li class="chapter" data-level="8.14" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#outlying-values"><i class="fa fa-check"></i><b>8.14</b> Outlying values</a></li>
<li class="chapter" data-level="8.15" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#leverage"><i class="fa fa-check"></i><b>8.15</b> Leverage</a></li>
<li class="chapter" data-level="8.16" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#studentized-residuals"><i class="fa fa-check"></i><b>8.16</b> Studentized residuals</a></li>
<li class="chapter" data-level="8.17" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#cooks-distance"><i class="fa fa-check"></i><b>8.17</b> Cook’s distance</a></li>
<li class="chapter" data-level="8.18" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#social-media-marketing"><i class="fa fa-check"></i><b>8.18</b> Social media marketing</a></li>
<li class="chapter" data-level="8.19" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#extracting-values-from-models-in-r"><i class="fa fa-check"></i><b>8.19</b> Extracting values from models in R</a></li>
<li class="chapter" data-level="8.20" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#non-parametric-regression"><i class="fa fa-check"></i><b>8.20</b> Non-parametric regression</a>
<ul>
<li class="chapter" data-level="8.20.1" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#loess"><i class="fa fa-check"></i><b>8.20.1</b> LOESS</a></li>
</ul></li>
<li class="chapter" data-level="8.21" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#how-span-changes-the-loess-fit"><i class="fa fa-check"></i><b>8.21</b> How <code>span</code> changes the loess fit</a></li>
<li class="chapter" data-level="8.22" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#how-loess-works"><i class="fa fa-check"></i><b>8.22</b> How <code>loess</code> works</a></li>
<li class="chapter" data-level="8.23" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#us-economic-time-series"><i class="fa fa-check"></i><b>8.23</b> US economic time series</a></li>
<li class="chapter" data-level="8.24" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#how-to-fit-loess-curves-in-r"><i class="fa fa-check"></i><b>8.24</b> How to fit LOESS curves in R?</a>
<ul>
<li class="chapter" data-level="8.24.1" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#model-fitting"><i class="fa fa-check"></i><b>8.24.1</b> Model fitting</a></li>
<li class="chapter" data-level="8.24.2" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#showing-it-on-the-plot"><i class="fa fa-check"></i><b>8.24.2</b> Showing it on the plot</a></li>
</ul></li>
<li class="chapter" data-level="8.25" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#why-non-parametric-regression"><i class="fa fa-check"></i><b>8.25</b> Why non-parametric regression?</a></li>
<li class="chapter" data-level="8.26" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#bluegills"><i class="fa fa-check"></i><b>8.26</b> Bluegills</a></li>
<li class="chapter" data-level="8.27" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#soil-resistivity-in-a-field"><i class="fa fa-check"></i><b>8.27</b> Soil resistivity in a field</a></li>
<li class="chapter" data-level="8.28" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#conditioning-plots-coplots"><i class="fa fa-check"></i><b>8.28</b> Conditioning plots (Coplots)</a></li>
<li class="chapter" data-level="8.29" data-path="sculpting-data-using-models.html"><a href="sculpting-data-using-models.html#coplots-via-ggplot2"><i class="fa fa-check"></i><b>8.29</b> Coplots via <code>ggplot2</code></a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="exploring-data-having-a-space-and-time-context.html"><a href="exploring-data-having-a-space-and-time-context.html"><i class="fa fa-check"></i><b>9</b> Exploring data having a space and time context</a></li>
<li class="chapter" data-level="10" data-path="is-what-you-see-really-there.html"><a href="is-what-you-see-really-there.html"><i class="fa fa-check"></i><b>10</b> Is what you see really there?</a>
<ul>
<li class="chapter" data-level="10.1" data-path="is-what-you-see-really-there.html"><a href="is-what-you-see-really-there.html#revisiting-hypothesis-testing"><i class="fa fa-check"></i><b>10.1</b> Revisiting hypothesis testing</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="is-what-you-see-really-there.html"><a href="is-what-you-see-really-there.html#testing-coin-bias"><i class="fa fa-check"></i><b>10.1.1</b> Testing coin bias</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="is-what-you-see-really-there.html"><a href="is-what-you-see-really-there.html#frequentist-hypotheses-testing-framework"><i class="fa fa-check"></i><b>10.2</b> (Frequentist) hypotheses testing framework</a></li>
<li class="chapter" data-level="10.3" data-path="is-what-you-see-really-there.html"><a href="is-what-you-see-really-there.html#judicial-system"><i class="fa fa-check"></i><b>10.3</b> Judicial system</a></li>
<li class="chapter" data-level="10.4" data-path="is-what-you-see-really-there.html"><a href="is-what-you-see-really-there.html#visual-inference"><i class="fa fa-check"></i><b>10.4</b> Visual inference</a></li>
<li class="chapter" data-level="10.5" data-path="is-what-you-see-really-there.html"><a href="is-what-you-see-really-there.html#visual-inference-more-formally"><i class="fa fa-check"></i><b>10.5</b> Visual inference more formally</a></li>
<li class="chapter" data-level="10.6" data-path="is-what-you-see-really-there.html"><a href="is-what-you-see-really-there.html#uniformity-trial-of-peanuts"><i class="fa fa-check"></i><b>10.6</b> Uniformity trial of peanuts</a></li>
<li class="chapter" data-level="10.7" data-path="is-what-you-see-really-there.html"><a href="is-what-you-see-really-there.html#statistical-significance-and-practical-significance"><i class="fa fa-check"></i><b>10.7</b> Statistical significance and practical significance</a></li>
<li class="chapter" data-level="10.8" data-path="is-what-you-see-really-there.html"><a href="is-what-you-see-really-there.html#statistical-significance-of-the-data-plot"><i class="fa fa-check"></i><b>10.8</b> Statistical significance of the data plot</a></li>
<li class="chapter" data-level="10.9" data-path="is-what-you-see-really-there.html"><a href="is-what-you-see-really-there.html#lineup-of-small-effect-difference"><i class="fa fa-check"></i><b>10.9</b> Lineup of small effect difference</a></li>
<li class="chapter" data-level="10.10" data-path="is-what-you-see-really-there.html"><a href="is-what-you-see-really-there.html#some-considerations-in-visual-inference"><i class="fa fa-check"></i><b>10.10</b> Some considerations in visual inference</a></li>
<li class="chapter" data-level="10.11" data-path="is-what-you-see-really-there.html"><a href="is-what-you-see-really-there.html#visual-inference-with-the-nullabor"><i class="fa fa-check"></i><b>10.11</b> Visual inference with the <code>nullabor</code> 📦</a></li>
<li class="chapter" data-level="10.12" data-path="is-what-you-see-really-there.html"><a href="is-what-you-see-really-there.html#potato-scab-infection"><i class="fa fa-check"></i><b>10.12</b> Potato scab infection</a></li>
<li class="chapter" data-level="10.13" data-path="is-what-you-see-really-there.html"><a href="is-what-you-see-really-there.html#black-cherry-trees"><i class="fa fa-check"></i><b>10.13</b> Black Cherry Trees</a></li>
<li class="chapter" data-level="10.14" data-path="is-what-you-see-really-there.html"><a href="is-what-you-see-really-there.html#temperatures-of-stars"><i class="fa fa-check"></i><b>10.14</b> Temperatures of stars</a></li>
<li class="chapter" data-level="10.15" data-path="is-what-you-see-really-there.html"><a href="is-what-you-see-really-there.html#foreign-exchange-rate"><i class="fa fa-check"></i><b>10.15</b> Foreign exchange rate</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>11</b> Final words</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href= https://github.com/dicook/exploratory-data-analysis-in-the-21st-century" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Exploratory Data Analysis in the 21st Century</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="what-is-eda" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> What is exploratory data analysis?<a href="what-is-eda.html#what-is-eda" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Exploratory data analysis is a term that became popular after John Tukey published his seminal book on the topic in 1977 <span class="citation">(<a href="#ref-tukey77">J. Tukey 1977</a>)</span>. What is actually refers to, though, is not very well-defined.</p>
<div id="common-descriptions" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Common descriptions<a href="what-is-eda.html#common-descriptions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<!-- Some common explanations -->
<p>EDA today is prevalent, and there are many descriptions. It’s interesting to compare and contrast these, in relation to the original scope.</p>
<p>From <a href="https://en.wikipedia.org/wiki/Exploratory_data_analysis">wikipedia</a></p>
<blockquote>
<p>In statistics, exploratory data analysis (EDA) is an approach to analyzing data sets to summarize their main characteristics, often with visual methods. A statistical model can be used or not, but primarily EDA is for seeing what the data can tell us beyond the formal modeling or hypothesis testing task.</p>
</blockquote>
<p>In <span class="citation">Wickham and Grolemund (<a href="#ref-r4ds">2017</a>)</span></p>
<blockquote>
<p>EDA is not a formal process with a strict set of rules. More than anything, EDA is a state of mind. During the initial phases of EDA you should feel free to investigate every idea that occurs to you. Some of these ideas will pan out, and some will be dead ends.</p>
</blockquote>
<p>The <a href="https://www.itl.nist.gov/div898/handbook/eda/section1/eda11.htm">National Institute of Standards and Technology</a></p>
<blockquote>
<p>Exploratory Data Analysis (EDA) is an approach/philosophy for data analysis that employs a variety of techniques (mostly graphical) to (1) maximize insight into a data set; (2) uncover underlying structure; (3) extract important variables; (4) detect outliers and anomalies; (5) test underlying assumptions; (6) develop parsimonious models; and (7) determine optimal factor settings.</p>
</blockquote>
<p>The predictive analytics competition site <a href="https://www.kaggle.com/pavansanagapati/a-simple-tutorial-on-exploratory-data-analysis">Kaggle</a> says</p>
<blockquote>
<p>What is Exploratory Data Analysis (EDA)? (1) How to ensure you are ready to use machine learning algorithms in a project? (2) How to choose the most suitable algorithms for your data set? (3) How to define the feature variables that can potentially be used for machine learning?</p>
</blockquote>
<p>Legacy data analysis software system <a href="https://seleritysas.com/blog/2020/05/08/exploratory-data-analysis-and-its-role-in-improving-business-operations/">SAS</a> says</p>
<blockquote>
<p>EDA is necessary for the next stage of data research. If there was an analogy to exploratory data analysis, it would be that of a painter examining their tools and available time, before deciding on what best to paint.</p>
</blockquote>
<p>The massive online <a href="https://www.coursera.org/learn/exploratory-data-analysis#syllabus">John Hopkins EDA class</a> describes it as</p>
<blockquote>
<p>These techniques are typically applied before formal modeling commences and can help inform the development of more complex statistical models. Exploratory techniques are also important for eliminating or sharpening potential hypotheses about the world that can be addressed by the data.</p>
</blockquote>
<p>General information site <a href="https://towardsdatascience.com/if-you-dont-find-anything-new-you-don-t-do-eda-right-d356f9995098">Towards Data Science</a> says</p>
<blockquote>
<p>The purpose of doing the Exploratory Data Analysis or EDA is to find new information in data. The understanding of EDA that practitioners may not aware of, is the EDA uses a visually-examined dataset to understand and summarize the main characteristics of the dataset without having a prior hypothesis or relying upon statistical models.</p>
</blockquote>
</div>
<div id="components-of-data-analysis" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Components of data analysis<a href="what-is-eda.html#components-of-data-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Data analysis is a process of cleaning, transforming,
inspecting and modelling data with the aim of extracting
information. It might be exploratory or confirmatory, descriptive of predictive.</p>
<!-- Modeling and prediction -->
<p>Before modelling and predicting, data should first be explored to uncover the patterns and structures that exist. Data analysis involves both numerical and visual techniques designed to reveal interesting information that may be hidden in the data. However, an analyst must be cautious not to over-interpret apparent patterns, and to make efforts assess the results of an analysis are reliable for the data being studied and potentially for new data.</p>
<!-- Inference -->
<p>In a confirmatory data analysis (CDA), the focus is on answering a particular question, and includes processes such as testing hypothesis, model selection, or predictive modelling for the purposes of statistical inference. An important part of this is to check the sometimes strict assumptions made in order to conduct inference, and that problems in the data don’t compromise the inference. This is usually called <em>initial data analysis</em>. In addition, computing <em>model diagnostics</em>, like making residual plots, is an important part of checking that a predictive model appropriately fits the data.</p>
</div>
<div id="differentiating-eda-from-cda" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Differentiating EDA from CDA<a href="what-is-eda.html#differentiating-eda-from-cda" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="from-the-case-study" class="section level3 hasAnchor" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> From the case study<a href="what-is-eda.html#from-the-case-study" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><em>Back-story</em>: In 1995 I (Di), as a newly fledged assistant professor, was asked to teach a Business Statistics course. In the process of looking for appropriate examples, I found a book titled “Practical Data Analysis: Case Studies in Business Statistics” by Bryant and Smith <span class="citation">(<a href="#ref-bryantsmith1995">Bryant and Smith 1995</a>)</span>. The example on tipping in restaurants caught my eye, because I had always found tipping to be a difficult. Perhaps this was because I was an Australian new to the practice after moving to the USA for graduate school, in 1988 and still uncomfortable with the culture almost a decade later. The types of questions that bounce around mentally, should I tip because the wait staff’s wage comes mostly from this money, how much does the restaurant owner take from the worker, was the service good, have I just been paid and can be generous.</p>
<div id="whatistipping" class="section level4 unnumbered hasAnchor">
<h4>What is tipping?<a href="what-is-eda.html#whatistipping" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>According to <a href="https://www.washingtonpost.com/news/going-out-guide/wp/2016/09/15/tipping-can-be-complicated-these-are-the-basic-rules-you-should-know-about/">The basic rules of tipping that everyone should know about</a>:</p>
<ul>
<li>When you’re dining at a full-service restaurant
<ul>
<li>Tip 20 percent of your full bill.</li>
</ul></li>
<li>When you grab a cup of coffee
<ul>
<li>Round up or add a dollar if you’re a regular or ordered a complicated drink.</li>
</ul></li>
<li>When you have lunch at a food truck
<ul>
<li>Drop a few dollars into the tip jar, but a little less than you would at a dine-in spot.</li>
</ul></li>
<li>When you use a gift card
<ul>
<li>Tip on the total value of the meal, not just what you paid out of pocket.</li>
</ul></li>
</ul>
</div>
<div id="aboutthedata" class="section level4 unnumbered hasAnchor">
<h4>About the data<a href="what-is-eda.html#aboutthedata" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The tips case study data is described as follows:</p>
<blockquote>
<p>In one restaurant, a food server recorded the following data on all customers they served during an interval of two and a half months in early 1990.</p>
</blockquote>
<blockquote>
<p>Food servers’ tips in restaurants may be influenced by many factors, including the nature of the restaurant, size of the party, and table locations in the restaurant. Restaurant managers need to know which factors matter when they assign tables to food servers.</p>
</blockquote>
<p>and a description of the variables is as reported in <span class="citation">Cook and Swayne (<a href="#ref-cookswayne07">2007</a>)</span>:</p>
<p><img src="images/tips.png" width="90%"></p>
</div>
<div id="casestudyprocedure" class="section level4 unnumbered hasAnchor">
<h4>Case study procedure (which would be considered to be CDA)<a href="what-is-eda.html#casestudyprocedure" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To answer the question “What are the most important factors affecting tips?”, the analysis should follow these steps according to <span class="citation">Bryant and Smith (<a href="#ref-bryantsmith1995">1995</a>)</span>:</p>
<ol style="list-style-type: decimal">
<li>Develop a model
<ul>
<li>Should the response be <code>tip</code> alone and use the total bill as a predictor?</li>
<li>Should you create a new variable <code>tip rate</code> and use this as the response?</li>
</ul></li>
<li>Fit the full model with sex, smoker, day, time and size as predictors</li>
<li>Refine model: Should some variables should be dropped?</li>
<li>Check distribution of residuals</li>
<li>Summarise the model, if X=something, what would be the expected tip</li>
</ol>
</div>
<div id="step1" class="section level4 unnumbered hasAnchor">
<h4>Step 1<a href="what-is-eda.html#step1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Calculate tip % as tip/total bill <span class="math inline">\(\times\)</span> 100</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="what-is-eda.html#cb1-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="what-is-eda.html#cb1-2" tabindex="-1"></a>tips <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;http://ggobi.org/book/data/tips.csv&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="what-is-eda.html#cb2-1" tabindex="-1"></a>tips <span class="ot">&lt;-</span> tips <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="what-is-eda.html#cb2-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tip_pct =</span> tip<span class="sc">/</span>totbill <span class="sc">*</span> <span class="dv">100</span>) <span class="co">#&lt;&lt;</span></span></code></pre></div>
</div>
<div id="step2" class="section level4 unnumbered hasAnchor">
<h4>Step 2<a href="what-is-eda.html#step2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Fit the full model with all variables</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="what-is-eda.html#cb3-1" tabindex="-1"></a>tips_lm <span class="ot">&lt;-</span> tips <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="what-is-eda.html#cb3-2" tabindex="-1"></a>  <span class="fu">select</span>(tip_pct, sex, smoker, day, time, size) <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="what-is-eda.html#cb3-3" tabindex="-1"></a>  <span class="fu">lm</span>(tip_pct <span class="sc">~</span> ., <span class="at">data=</span>.) <span class="co">#&lt;&lt;</span></span></code></pre></div>
<p>Summarise the model</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="what-is-eda.html#cb4-1" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb4-2"><a href="what-is-eda.html#cb4-2" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb4-3"><a href="what-is-eda.html#cb4-3" tabindex="-1"></a><span class="fu">tidy</span>(tips_lm) <span class="sc">%&gt;%</span> <span class="co">#&lt;&lt;</span></span>
<span id="cb4-4"><a href="what-is-eda.html#cb4-4" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits=</span><span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb4-5"><a href="what-is-eda.html#cb4-5" tabindex="-1"></a>  <span class="fu">kable_styling</span>() </span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
20.66
</td>
<td style="text-align:right;">
2.49
</td>
<td style="text-align:right;">
8.29
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
sexM
</td>
<td style="text-align:right;">
-0.85
</td>
<td style="text-align:right;">
0.83
</td>
<td style="text-align:right;">
-1.02
</td>
<td style="text-align:right;">
0.31
</td>
</tr>
<tr>
<td style="text-align:left;">
smokerYes
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:right;">
0.85
</td>
<td style="text-align:right;">
0.43
</td>
<td style="text-align:right;">
0.67
</td>
</tr>
<tr>
<td style="text-align:left;">
daySat
</td>
<td style="text-align:right;">
-0.18
</td>
<td style="text-align:right;">
1.83
</td>
<td style="text-align:right;">
-0.10
</td>
<td style="text-align:right;">
0.92
</td>
</tr>
<tr>
<td style="text-align:left;">
daySun
</td>
<td style="text-align:right;">
1.67
</td>
<td style="text-align:right;">
1.90
</td>
<td style="text-align:right;">
0.88
</td>
<td style="text-align:right;">
0.38
</td>
</tr>
<tr>
<td style="text-align:left;">
dayThu
</td>
<td style="text-align:right;">
-1.82
</td>
<td style="text-align:right;">
2.32
</td>
<td style="text-align:right;">
-0.78
</td>
<td style="text-align:right;">
0.43
</td>
</tr>
<tr>
<td style="text-align:left;">
timeNight
</td>
<td style="text-align:right;">
-2.34
</td>
<td style="text-align:right;">
2.61
</td>
<td style="text-align:right;">
-0.89
</td>
<td style="text-align:right;">
0.37
</td>
</tr>
<tr>
<td style="text-align:left;">
size
</td>
<td style="text-align:right;">
-0.96
</td>
<td style="text-align:right;">
0.42
</td>
<td style="text-align:right;">
-2.28
</td>
<td style="text-align:right;">
0.02
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="what-is-eda.html#cb5-1" tabindex="-1"></a><span class="fu">glance</span>(tips_lm) <span class="sc">%&gt;%</span> <span class="co">#&lt;&lt;</span></span>
<span id="cb5-2"><a href="what-is-eda.html#cb5-2" tabindex="-1"></a>  <span class="fu">select</span>(r.squared, statistic, p.value) <span class="sc">%&gt;%</span> </span>
<span id="cb5-3"><a href="what-is-eda.html#cb5-3" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits=</span><span class="dv">3</span>)</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:right;">
r.squared
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.042
</td>
<td style="text-align:right;">
1.479
</td>
<td style="text-align:right;">
0.175
</td>
</tr>
</tbody>
</table>
<p>From the model summary the most (and only) important variable for predicting tip is the size of the dining party. This decision is based on the <span class="math inline">\(t\)</span>-statistic and <span class="math inline">\(p\)</span>-values reported in the model summary. Size of the party is the only variable which has a really small <span class="math inline">\(p\)</span>-value. The small value indicates that it is very unlikely for the true parameter relating size of the party to tip % to be 0, that is, the relationship between these two variables is considered to be statistically significant. The same cannot be said for any of the other variables.</p>
</div>
<div id="step3" class="section level4 unnumbered hasAnchor">
<h4>Step 3<a href="what-is-eda.html#step3" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Refine the model, by using only one predictor, size of the dining party.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="what-is-eda.html#cb6-1" tabindex="-1"></a>tips_lm <span class="ot">&lt;-</span> tips <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="what-is-eda.html#cb6-2" tabindex="-1"></a>  <span class="fu">select</span>(tip_pct, size) <span class="sc">%&gt;%</span> <span class="co">#&lt;&lt;</span></span>
<span id="cb6-3"><a href="what-is-eda.html#cb6-3" tabindex="-1"></a>  <span class="fu">lm</span>(tip_pct <span class="sc">~</span> ., <span class="at">data=</span>.) </span>
<span id="cb6-4"><a href="what-is-eda.html#cb6-4" tabindex="-1"></a><span class="fu">tidy</span>(tips_lm) <span class="sc">%&gt;%</span> <span class="co">#&lt;&lt;</span></span>
<span id="cb6-5"><a href="what-is-eda.html#cb6-5" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits=</span><span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb6-6"><a href="what-is-eda.html#cb6-6" tabindex="-1"></a>  <span class="fu">kable_styling</span>() </span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
18.44
</td>
<td style="text-align:right;">
1.12
</td>
<td style="text-align:right;">
16.47
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
size
</td>
<td style="text-align:right;">
-0.92
</td>
<td style="text-align:right;">
0.41
</td>
<td style="text-align:right;">
-2.25
</td>
<td style="text-align:right;">
0.03
</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\widehat{tip %} = 18.44 - 0.92 \times size\]</span></p>
<p>As the size of the dining party increases by one person the tip decreases by approximately 1%.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="what-is-eda.html#cb7-1" tabindex="-1"></a><span class="fu">glance</span>(tips_lm) <span class="sc">%&gt;%</span> <span class="co">#&lt;&lt;</span></span>
<span id="cb7-2"><a href="what-is-eda.html#cb7-2" tabindex="-1"></a>  <span class="fu">select</span>(r.squared, statistic, p.value) <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="what-is-eda.html#cb7-3" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">`</span><span class="at">F statistic</span><span class="st">`</span> <span class="ot">=</span> statistic) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="what-is-eda.html#cb7-4" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits=</span><span class="dv">3</span>)</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:right;">
r.squared
</th>
<th style="text-align:right;">
F statistic
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
5.042
</td>
<td style="text-align:right;">
0.026
</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(R^2 = 0.02\)</span>.</p>
<p>This dropped by half from the full model, even though no other variables contributed significantly to the model. It might be possible to bring the <span class="math inline">\(R^2\)</span> up a little by adding interaction terms to the model, for example, sex, or smoker, and size of the party. We won’t don that here, because the purpose is to illustrate the difference between exploratory and confirmatory rather than fitting the best possible model.</p>
<p><strong>What do the <span class="math inline">\(F\)</span> statistic and <span class="math inline">\(p\)</span>-value mean?</strong></p>
<p>Assume that we have a random sample from a population. Assume that the model for the population is</p>
<p><span class="math display">\[ \widehat{tip %} = \beta_0 + \beta_1 sexM + ... + \beta_7 size \]</span>
and we have observed</p>
<p><span class="math display">\[ \widehat{tip %} = b_0 + b_1  sexM + ... + b_7 size \]</span>
The <span class="math inline">\(F\)</span> statistic refers to</p>
<p><span class="math display">\[ H_o: \beta_1 = ... = \beta_7 = 0 ~~ vs ~~ H_a: \text{at least one is not 0}\]</span>
The <span class="math inline">\(p\)</span>-value is the probability that we observe the given <span class="math inline">\(F\)</span> value or larger, computed assuming <span class="math inline">\(H_o\)</span> is true.</p>
<p><strong>What do the <span class="math inline">\(t\)</span> statistics and <span class="math inline">\(p\)</span>-value associated with model coeficients mean?</strong></p>
<p>Assume that we have a random sample from a population. Assume that the model for the population is</p>
<p><span class="math display">\[ \widehat{tip %} = \beta_0 + \beta_1 sexM + ... + \beta_7 size \]</span>
and we have observed</p>
<p><span class="math display">\[ \widehat{tip %} = b_0 + b_1  sexM + ... + b_7 size \]</span></p>
<p>The <span class="math inline">\(t\)</span> statistics in the coefficient summary refer to</p>
<p><span class="math display">\[ H_o: \beta_k = 0 ~~ vs ~~ H_a: \beta_k \neq 0 \]</span>
The <span class="math inline">\(p\)</span>-value is the probability that we observe the given <span class="math inline">\(t\)</span> value or more extreme, computed assuming <span class="math inline">\(H_o\)</span> is true.</p>
</div>
<div id="modelchecking" class="section level4 unnumbered hasAnchor">
<h4>Model checking<a href="what-is-eda.html#modelchecking" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Normally, the final model summary would be accompanied diagnostic plots</p>
<ul>
<li>observed vs fitted values to check strength and appropriateness of the fit</li>
<li>univariate plot, and normal probability plot, of residuals to check for normality</li>
<li>in the simple final model like this, the observed vs predictor, with model overlaid would be advised to assess the model relative to the variability around the model</li>
<li>when the final model has more terms, using a partial dependence plot to check the relative relationship between the response and predictors would be recommended.</li>
</ul>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="what-is-eda.html#cb8-1" tabindex="-1"></a>tips_aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(tips_lm)</span>
<span id="cb8-2"><a href="what-is-eda.html#cb8-2" tabindex="-1"></a><span class="fu">ggplot</span>(tips_aug, </span>
<span id="cb8-3"><a href="what-is-eda.html#cb8-3" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x=</span>.resid)) <span class="sc">+</span> <span class="co">#&lt;&lt;</span></span>
<span id="cb8-4"><a href="what-is-eda.html#cb8-4" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb8-5"><a href="what-is-eda.html#cb8-5" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;residuals&quot;</span>) </span></code></pre></div>
<p><img src="eda-book_files/figure-html/res_hist-1.png" width="90%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="what-is-eda.html#cb9-1" tabindex="-1"></a><span class="fu">ggplot</span>(tips_aug, </span>
<span id="cb9-2"><a href="what-is-eda.html#cb9-2" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">sample=</span>.resid)) <span class="sc">+</span> <span class="co">#&lt;&lt;</span></span>
<span id="cb9-3"><a href="what-is-eda.html#cb9-3" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb9-4"><a href="what-is-eda.html#cb9-4" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb9-5"><a href="what-is-eda.html#cb9-5" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;residuals&quot;</span>) <span class="sc">+</span></span>
<span id="cb9-6"><a href="what-is-eda.html#cb9-6" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="eda-book_files/figure-html/res_qq-1.png" width="90%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="what-is-eda.html#cb10-1" tabindex="-1"></a><span class="fu">ggplot</span>(tips_aug, </span>
<span id="cb10-2"><a href="what-is-eda.html#cb10-2" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x=</span>.fitted, <span class="at">y=</span>tip_pct)) <span class="sc">+</span> <span class="co">#&lt;&lt;</span></span>
<span id="cb10-3"><a href="what-is-eda.html#cb10-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb10-4"><a href="what-is-eda.html#cb10-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>) <span class="sc">+</span></span>
<span id="cb10-5"><a href="what-is-eda.html#cb10-5" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;observed&quot;</span>) <span class="sc">+</span></span>
<span id="cb10-6"><a href="what-is-eda.html#cb10-6" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;fitted&quot;</span>)</span></code></pre></div>
<p><img src="eda-book_files/figure-html/obs_fitted-1.png" width="90%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="what-is-eda.html#cb11-1" tabindex="-1"></a><span class="fu">ggplot</span>(tips_aug, </span>
<span id="cb11-2"><a href="what-is-eda.html#cb11-2" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x=</span>size, <span class="at">y=</span>tip_pct)) <span class="sc">+</span> <span class="co">#&lt;&lt;</span></span>
<span id="cb11-3"><a href="what-is-eda.html#cb11-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb11-4"><a href="what-is-eda.html#cb11-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>) <span class="sc">+</span></span>
<span id="cb11-5"><a href="what-is-eda.html#cb11-5" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;tip %&quot;</span>)</span></code></pre></div>
<p><img src="eda-book_files/figure-html/fitted_model-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>The result of this work would leave us with a model that could be used to impose a dining/tipping policy in restaurants (see <a href="https://travel.stackexchange.com/questions/40543/can-i-refuse-to-pay-auto-gratuity-in-a-restaurant">here</a>) and should also leave us with an unease that this policy is based on weak support.</p>
</div>
<div id="summarise-the-model-and-answer-the-question" class="section level4 hasAnchor" number="2.3.1.1">
<h4><span class="header-section-number">2.3.1.1</span> Summarise the model, and answer the question<a href="what-is-eda.html#summarise-the-model-and-answer-the-question" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The answer to the original question is that the only important factor affecting tip is the size of the dining party.</p>
<p>The final model is</p>
<p><span class="math display">\[\widehat{tip %} = 18.44 - 0.92 \times size\]</span></p>
<p>The interpretation of the model is, <em>as the size of the dining party increases by one person the tip decreases by approximately 1%</em>.</p>
<p><strong>What does <span class="math inline">\(R^2 = 0.02\)</span> mean?</strong></p>
<p><span class="math inline">\(R^2 = 0.02\)</span> means that size explains just 2% of the variance in tip %. This is a very weak model.</p>
<p>And <span class="math inline">\(R^2 = 0.04\)</span> is also a very weak model.</p>
</div>
<div id="overview-of-cda-process" class="section level4 hasAnchor" number="2.3.1.2">
<h4><span class="header-section-number">2.3.1.2</span> Overview of CDA process<a href="what-is-eda.html#overview-of-cda-process" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In this example, the analysis has basically followed the CDA process outlined in Figure <a href="what-is-eda.html#fig:cda">2.1</a>. It started from a specific and clearly defined question, skipped the IDA, to go straight into modeling, followed by diagnostics, which should have been finished with a statement of conclusion.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:cda"></span>
<div class="grViz html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-4e5333c4ee50526f0517" style="width:90%;height:384px;"></div>
<script type="application/json" data-for="htmlwidget-4e5333c4ee50526f0517">{"x":{"diagram":"digraph {\n\ngraph [layout = \"dot\",\n       rankdir = \"TB\",\n       outputorder = \"edgesfirst\",\n       bgcolor = \"white\"]\n\nnode [fontname = \"Helvetica\",\n      fontsize = \"10\",\n      shape = \"circle\",\n      fixedsize = \"true\",\n      width = \"0.5\",\n      style = \"filled\",\n      fillcolor = \"aliceblue\",\n      color = \"gray70\",\n      fontcolor = \"gray50\"]\n\nedge [fontname = \"Helvetica\",\n     fontsize = \"8\",\n     len = \"1.5\",\n     color = \"gray80\",\n     arrowsize = \"0.5\"]\n\n  \"1\" [label = \"question/hypothesis\", shape = \"rectangle\", width = \"3.2\", fontsize = \"24\", fillcolor = \"#E5E5E5\", fontcolor = \"#000000\"] \n  \"2\" [label = \"data\", shape = \"rectangle\", width = \"1\", fontsize = \"24\", fillcolor = \"#E5E5E5\", fontcolor = \"#000000\"] \n  \"3\" [label = \"IDA\", shape = \"rectangle\", width = \"1\", fontsize = \"24\", fillcolor = \"#E5E5E5\", fontcolor = \"#000000\"] \n  \"4\" [label = \"model/test\", shape = \"rectangle\", width = \"1.8\", fontsize = \"24\", fillcolor = \"#E5E5E5\", fontcolor = \"#000000\"] \n  \"5\" [label = \"MD\", shape = \"rectangle\", width = \"1\", fontsize = \"24\", fillcolor = \"#E5E5E5\", fontcolor = \"#000000\"] \n  \"6\" [label = \"conclusion\", shape = \"rectangle\", width = \"2.1\", fontsize = \"24\", fillcolor = \"#E5E5E5\", fontcolor = \"#000000\"] \n\"1\"->\"2\" [color = \"black\"] \n\"2\"->\"3\" [color = \"black\"] \n\"3\"->\"4\" [color = \"black\"] \n\"4\"->\"5\" [color = \"black\"] \n\"5\"->\"6\" [color = \"black\"] \n}","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
<p class="caption">
Figure 2.1: Pipeline of confirmatory data analysis. It starts with a question.
</p>
</div>
</div>
</div>
<div id="eda-approach" class="section level3 hasAnchor" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> EDA approach<a href="what-is-eda.html#eda-approach" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>First, examine the data description, and the explanation of the variables. In the tips example, this would be:</p>
<ul>
<li>tip and totbill are quantitative, but generally we would think about tip as a percentage of the bill, so creating this new variable would be useful, too.</li>
<li>sex, smoker, day, time of day are categorical.</li>
<li>size is discrete/integer.</li>
</ul>
<p>The types of variables suggest what summaries to make.</p>
<p>For the quantitative variables we would calculate</p>
<ul>
<li>means, standard deviations, median, quartiles, minimum and maximum, and</li>
<li>also make histograms or density plots and scatterplots to explore bivariate relationships.</li>
</ul>
<p>For categorical variables, and integer variables with few categories, compute</p>
<ul>
<li>counts and proportions, and</li>
<li>make bar charts and mosaic plots</li>
</ul>
<p>Thinking about relationships between categorical and quantitative variables, we could
- calculate the numerical summaries by the categorical variable levels, and
- make histograms and scatterplots, facetted by the categorical variables.</p>
<div id="tip" class="section level4 unnumbered hasAnchor">
<h4>Look at the distribution of tips, total bill.<a href="what-is-eda.html#tip" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="what-is-eda.html#cb12-1" tabindex="-1"></a><span class="fu">ggplot</span>(tips, </span>
<span id="cb12-2"><a href="what-is-eda.html#cb12-2" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x=</span>tip)) <span class="sc">+</span> <span class="co">#&lt;&lt;</span></span>
<span id="cb12-3"><a href="what-is-eda.html#cb12-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb12-4"><a href="what-is-eda.html#cb12-4" tabindex="-1"></a>    <span class="at">colour=</span><span class="st">&quot;white&quot;</span>)  </span></code></pre></div>
<p><img src="eda-book_files/figure-html/tips-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Because, one binwidth is never enough …</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="what-is-eda.html#cb13-1" tabindex="-1"></a><span class="fu">ggplot</span>(tips, </span>
<span id="cb13-2"><a href="what-is-eda.html#cb13-2" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x=</span>tip)) <span class="sc">+</span></span>
<span id="cb13-3"><a href="what-is-eda.html#cb13-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb13-4"><a href="what-is-eda.html#cb13-4" tabindex="-1"></a>    <span class="at">breaks=</span><span class="fu">seq</span>(<span class="fl">0.5</span>,<span class="fl">10.5</span>,<span class="dv">1</span>), <span class="co">#&lt;&lt; </span></span>
<span id="cb13-5"><a href="what-is-eda.html#cb13-5" tabindex="-1"></a>    <span class="at">colour=</span><span class="st">&quot;white&quot;</span>) <span class="sc">+</span> </span>
<span id="cb13-6"><a href="what-is-eda.html#cb13-6" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(</span>
<span id="cb13-7"><a href="what-is-eda.html#cb13-7" tabindex="-1"></a>    <span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">11</span>,<span class="dv">1</span>))</span></code></pre></div>
<p><img src="eda-book_files/figure-html/tips2-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Big fat bins. Tips are skewed, which means most tips are relatively small.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="what-is-eda.html#cb14-1" tabindex="-1"></a><span class="fu">ggplot</span>(tips, </span>
<span id="cb14-2"><a href="what-is-eda.html#cb14-2" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x=</span>tip)) <span class="sc">+</span> </span>
<span id="cb14-3"><a href="what-is-eda.html#cb14-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb14-4"><a href="what-is-eda.html#cb14-4" tabindex="-1"></a>    <span class="at">breaks=</span><span class="fu">seq</span>(<span class="fl">0.5</span>,<span class="fl">10.5</span>,<span class="fl">0.1</span>), <span class="co">#&lt;&lt;</span></span>
<span id="cb14-5"><a href="what-is-eda.html#cb14-5" tabindex="-1"></a>    <span class="at">colour=</span><span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb14-6"><a href="what-is-eda.html#cb14-6" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(</span>
<span id="cb14-7"><a href="what-is-eda.html#cb14-7" tabindex="-1"></a>    <span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">11</span>,<span class="dv">1</span>))</span></code></pre></div>
<p><img src="eda-book_files/figure-html/tips3-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Skinny bins. Tips are multimodal, and occurring at the full dollar and 50c amounts.</p>
</div>
<div id="tiptotal" class="section level4 unnumbered hasAnchor">
<h4>Relationship between tip and total<a href="what-is-eda.html#tiptotal" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="what-is-eda.html#cb15-1" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(tips, </span>
<span id="cb15-2"><a href="what-is-eda.html#cb15-2" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x=</span>totbill, <span class="at">y=</span>tip)) <span class="sc">+</span> </span>
<span id="cb15-3"><a href="what-is-eda.html#cb15-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="co">#&lt;&lt;</span></span>
<span id="cb15-4"><a href="what-is-eda.html#cb15-4" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb15-5"><a href="what-is-eda.html#cb15-5" tabindex="-1"></a>    <span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">11</span>,<span class="dv">1</span>))</span>
<span id="cb15-6"><a href="what-is-eda.html#cb15-6" tabindex="-1"></a>p</span></code></pre></div>
<p><img src="eda-book_files/figure-html/tips_tot-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Adding a regression line, helps to focus on a tipping standard, and whether individual tips are above or below expected.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="what-is-eda.html#cb16-1" tabindex="-1"></a>p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">geom_abline</span>(<span class="at">intercept=</span><span class="dv">0</span>, <span class="co">#&lt;&lt;</span></span>
<span id="cb16-2"><a href="what-is-eda.html#cb16-2" tabindex="-1"></a>              <span class="at">slope=</span><span class="fl">0.2</span>) <span class="sc">+</span> <span class="co">#&lt;&lt;</span></span>
<span id="cb16-3"><a href="what-is-eda.html#cb16-3" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x=</span><span class="dv">45</span>, <span class="at">y=</span><span class="dv">10</span>, </span>
<span id="cb16-4"><a href="what-is-eda.html#cb16-4" tabindex="-1"></a>           <span class="at">label=</span><span class="st">&quot;20% tip&quot;</span>) </span>
<span id="cb16-5"><a href="what-is-eda.html#cb16-5" tabindex="-1"></a>p</span></code></pre></div>
<p><img src="eda-book_files/figure-html/tips_tot2-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Most tips less than 20%, there are more “skin flints” than generous diners. There are a couple of big tips, and we can see the banding horizontally that is the rounding seen from the histogram of tips.</p>
</div>
<div id="tipcategorical" class="section level4 unnumbered hasAnchor">
<h4>Examine the distributions across categorical variables.<a href="what-is-eda.html#tipcategorical" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="what-is-eda.html#cb17-1" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">facet_grid</span>(smoker<span class="sc">~</span>sex) <span class="co">#&lt;&lt;</span></span></code></pre></div>
<p><img src="eda-book_files/figure-html/tips_sexsmoke-1.png" width="90%" style="display: block; margin: auto;" /></p>
<ul>
<li>The bigger bills tend to be paid by men (and females that smoke).</li>
<li>Except for three diners, female non-smokers are very consistent tippers, probably around 15-18% though.</li>
<li>The variability in the smokers is much higher than for the non-smokers.</li>
</ul>
<p><strong>Isn’t this interesting?</strong></p>
</div>
<div id="overview-of-eda-process" class="section level4 hasAnchor" number="2.3.2.1">
<h4><span class="header-section-number">2.3.2.1</span> Overview of EDA process<a href="what-is-eda.html#overview-of-eda-process" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The process of EDA here roughly follows the outline provided in Figure <a href="what-is-eda.html#fig:eda">2.2</a>. It started from looking at what variables were available in the data provided, followed by thinking about the different ways we might look at them. These implicitly defined relevant questions. Then we studied each plot, describing what patterns were visible, what these suggested, and whether this was surprising. These are common steps in EDA. One aspect that wasn’t done that is an exciting new approach is using modern computational inference, to help answer whether the patterns are surprising or not.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:eda"></span>
<div class="grViz html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-e7a02a1de21c2b4b5927" style="width:90%;height:384px;"></div>
<script type="application/json" data-for="htmlwidget-e7a02a1de21c2b4b5927">{"x":{"diagram":"digraph {\n\ngraph [layout = \"dot\",\n       rankdir = \"TB\",\n       outputorder = \"edgesfirst\",\n       bgcolor = \"white\"]\n\nnode [fontname = \"Helvetica\",\n      fontsize = \"10\",\n      shape = \"circle\",\n      fixedsize = \"true\",\n      width = \"0.5\",\n      style = \"filled\",\n      fillcolor = \"aliceblue\",\n      color = \"gray70\",\n      fontcolor = \"gray50\"]\n\nedge [fontname = \"Helvetica\",\n     fontsize = \"8\",\n     len = \"1.5\",\n     color = \"gray80\",\n     arrowsize = \"0.5\"]\n\n  \"1\" [label = \"what variables are in the data, and how was it collected?\", shape = \"rectangle\", width = \"9\", fontsize = \"24\", fillcolor = \"#E5E5E5\", fontcolor = \"#000000\"] \n  \"2\" [label = \"lots of open-ended questions\", shape = \"rectangle\", width = \"5\", fontsize = \"24\", fillcolor = \"#E5E5E5\", fontcolor = \"#000000\"] \n  \"3\" [label = \"lots of plots and numerical summaries and even models\", shape = \"rectangle\", width = \"9\", fontsize = \"24\", fillcolor = \"#E5E5E5\", fontcolor = \"#000000\"] \n  \"4\" [label = \"what do you see\", shape = \"rectangle\", width = \"3\", fontsize = \"24\", fillcolor = \"#E5E5E5\", fontcolor = \"#000000\"] \n  \"5\" [label = \"are these patterns likely to occur by chance\", shape = \"rectangle\", width = \"7\", fontsize = \"24\", fillcolor = \"#E5E5E5\", fontcolor = \"#000000\"] \n  \"6\" [label = \"summarise findings\", shape = \"rectangle\", width = \"4\", fontsize = \"24\", fillcolor = \"#E5E5E5\", fontcolor = \"#000000\"] \n\"1\"->\"2\" [color = \"black\"] \n\"2\"->\"3\" [color = \"black\"] \n\"3\"->\"4\" [color = \"black\"] \n\"4\"->\"5\" [color = \"black\"] \n\"5\"->\"6\" [color = \"black\"] \n}","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
<p class="caption">
Figure 2.2: Pipeline of exploratory data analysis. It starts with the data.
</p>
</div>
</div>
</div>
<div id="what-we-learned-from-eda" class="section level3 hasAnchor" number="2.3.3">
<h3><span class="header-section-number">2.3.3</span> What we learned from EDA<a href="what-is-eda.html#what-we-learned-from-eda" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the above example we gained a wealth of insight in a short time. Using nothing but graphical methods we investigated univariate, bivariate, and multivariate relationships. We found both global features and local detail. We saw that tips were rounded; then we saw the obvious correlation between the tip and the size of the bill, noting the scarcity of generous tippers; finally we discovered differences in the tipping behavior of male and female smokers and non-smokers.</p>
<p>Notice that we used very simple plots to explore some pretty complex relationships involving as many as four variables. Each plot shows a subset obtained by partitioning the data according to two binary variables. The statistical term for partitioning based on variables is “conditioning.” For example, the top left plot shows the dining parties that meet the condition that the bill payer was a male non-smoker: sex = male and smoking = False. In database terminology this plot would be called the result of “drill-down”. The idea of conditioning is richer than drill-down because it involves a structured partitioning of all data as opposed to the extraction of a single partition.</p>
<p>Having generated the four plots, we arrange them in a two-by-two layout to reflect the two variables on which we conditioned. Although the axes in each plot are tip and bill, the axes of the overall figure are smoking (vertical) and sex (horizontal). The arrangement permits us to make several kinds of comparisons and to make observations about the partitions.</p>
</div>
<div id="reality-check" class="section level3 hasAnchor" number="2.3.4">
<h3><span class="header-section-number">2.3.4</span> Reality check<a href="what-is-eda.html#reality-check" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The preceding explanations may have given a somewhat misleading impression of the process of data analysis. In our account the data had no problems; for example, there were no missing values and no recording errors. Every step was logical and necessary. Every question we asked had a meaningful answer. Every plot that was produced was useful and informative. In actual data analysis, nothing could be further from the truth. Real datasets are rarely perfect; most choices are guided by intuition, knowledge, and judgment; most steps lead to dead ends; most plots end up in the wastebasket. This may sound daunting, but even though data analysis is a highly improvisational activity, it can be given some structure nonetheless.</p>
</div>
<div id="what-is-eda-1" class="section level3 hasAnchor" number="2.3.5">
<h3><span class="header-section-number">2.3.5</span> What is EDA?<a href="what-is-eda.html#what-is-eda-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this stage in the analysis, we make time to “play in the sand” to allow us to find the unexpected, and come to some understanding of our data. We like to think of this as a little like traveling. We may have a purpose in visiting a new city, perhaps to attend a conference, but we need to take care of our basic necessities, such as finding eating places and gas stations. Some of our movements will be pre-determined, or guided by the advice of others, but some of the time we wander around by ourselves. We may find a cafe we particularly like or a cheaper gas station. This is all about getting to know the neighborhood.</p>
<p>EDA has always depended heavily on graphics, even before the term data visualization was coined. Our favorite quote from John Tukey’s rich legacy is that we need good pictures to <em>“force the unexpected upon us.”</em></p>
</div>
<div id="isnt-it-data-snooping" class="section level3 hasAnchor" number="2.3.6">
<h3><span class="header-section-number">2.3.6</span> Isn’t it data snooping?<a href="what-is-eda.html#isnt-it-data-snooping" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Because EDA is very graphical, it sometimes gives rise to a suspicion that patterns in the data are being detected and reported that are not really there.</li>
<li>So many different combinations may be examined, that something is bound to be interesting.</li>
<li>☠️ Structure seen in the plot drives hypothesis testing (on same data).</li>
</ul>
<p><em>Sometimes this is called data snooping.</em></p>
<p>We snooped into the tips data, and from a few plots we learned an enormous amount of information about tipping: There is a scarcity of generous tippers, the variability in tips increases extraordinarily for smoking parties, and people tend to round their tips. These are very different types of tipping behaviors than what we learned from the regression model. The regression model was not compromised by what we learned from graphics, and indeed, <em>we have a richer and more informative analysis. Making plots of the data is just smart.</em></p>
<p><strong>False discovery is the lesser danger when compared to non-discovery. Non-discovery is the failure to identify meaningful structure, and it may result in false or incomplete modeling. In a healthy scientific enterprise, the fear of non-discovery should be at least as great as the fear of false discovery.</strong></p>
</div>
<div id="why-arent-there-more-resources-on-eda" class="section level3 hasAnchor" number="2.3.7">
<h3><span class="header-section-number">2.3.7</span> Why aren’t there more resources on EDA?<a href="what-is-eda.html#why-arent-there-more-resources-on-eda" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Teaching data analysis is not easy, and the time allowed is always far from sufficient. But these difficulties have been enhanced by the view that “avoidance of cookbookery and growth of understanding come only by mathematical treatment, with emphasis upon proofs.” The problem of cookbookery is not peculiar to data analysis. But the solution of concentrating upon mathematics and proof is. <span class="citation">J. W. Tukey (<a href="#ref-tukey1962">1962</a>)</span></p>
</blockquote>
<p>There are many courses now, every introductory statistics course begins with exploratory data analysis, and teaches box plots. It is just a simple treatment, though. A book by <a href="https://bookdown.org/rdpeng/exdata/">Peng</a>, and a <a href="https://www.coursera.org/learn/exploratory-data-analysis">Coursera class by Peng, Leek and Caffo</a> with more than a 100,000 regularly enrolled.</p>
<center>
<ADD SOFTWARE TOO>
</center>
<p><strong>But we argue that there is something missing from all of this. Almost all of these resources focus on what would be called initial data analysis. These don’t capture the spirit of EDA, as introduced by Tukey.</strong></p>
</div>
</div>
<div id="the-origins-of-eda" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> The origins of EDA<a href="what-is-eda.html#the-origins-of-eda" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The field of exploratory data analysis came of age with the appearance of Exploratory Data Analysis <span class="citation">(<a href="#ref-tukey77">J. Tukey 1977</a>)</span>.</p>
<center>
<img src="images/tukey_cover.png" width="50%">
</center>
<p><em>Tukey held that too much emphasis in statistics was placed on statistical hypothesis testing (confirmatory data analysis); more emphasis needed to be placed on using data to suggest hypotheses to test.</em></p>
<div class="do">
<p>Take a glimpse back in time is possible with the <a href="http://stat-graphics.org/movies/">American Statistical Association video lending library</a>.</p>
<p>Watch <a href="https://www.youtube.com/embed/B7XoW2qiFUA">John Tukey talking about exploring high-dimensional data with an amazing new computer in 1973</a>, four years before the EDA book. Look out for these things:</p>
<ul>
<li>Tukey’s expertise is described as <em>for trial and error learning</em> and</li>
<li>the computing equipment, especially how the human interacted with the screen,</li>
<li>and the hair style of Jerry Friedman.</li>
</ul>
<p>The first 4.25 minutes are the best!</p>
</div>
<p>The orange book was written NOT to convince readers of the usefulness of EDA, NOT to provide a set of case studies, but to provide a huge number of individual and isolated techniques that data analysts might find useful in their work. In this sense the book contains a wealth of data analysis wisdom, which also make it a bit impenetrable, and perhaps best read is small increments. When you do that you’ll find an amazing collection of creative ways to “scratch down numbers” peppered with snippets of wisdom for working with data. Here are a few of our favourite snippets from the text, revealing words of wisdom.</p>
<ul>
<li><strong>It is important to understand what you CAN DO before you learn to measure how WELL you seem to have DONE it.</strong> Learning first what you can do will help you to work more easily and effectively.</li>
<li>A basic problem about any body of data is to make it <strong>more easily and effectively handleable by minds – our minds, her mind, his mind</strong>. To this general end:
<ul>
<li>anything that make a simpler description possible makes the description more easily handleable.</li>
<li>anything that looks below the previously described surface makes the description more effective.</li>
</ul></li>
<li>So we shall always be glad (a) to simplify description and (b) to describe one layer deeper. In particular,
<ul>
<li>to be able to say that we looked one layer deeper, and found nothing, is a definite step forward – though not as far as to be <strong>able to say that we looked deeper and found thus-and-such</strong>.</li>
<li>to be able to say that “if we change our point of view in the following way … things are simpler” is always a gain–though not quite so much as to be able to say “if we don’t bother to change our point of view (some other) things are equally simple.”</li>
</ul></li>
<li>Consistent with this view, we believe, is a clear demand that pictures based on exploration of data should <em>force</em> their messages upon us.
<ul>
<li><strong>Pictures that emphasize what we already know–“security blankets” to reassure us–are frequently not worth the space they take</strong>.</li>
<li>Pictures that have to be gone over with a reading glass to see the main point are wasteful of time and inadequate of effect.</li>
<li><strong>The greatest value of a picture</strong> is when it <em>forces</em> us to notice <strong>what we never expected to see.</strong></li>
</ul></li>
<li><strong>Once upon a time, statisticians only explored.</strong> Then they learned to confirm exactly–to confirm a few things exactly, each under very specific circumstances. As they emphasized exact confirmation, their techniques inevitably became less flexible. The connection of the most used techniques with past insights was weakened. Anything to which confirmatory procedure was not explicitly attached was decried as “mere descriptive statistics”, no matter how much we learned from it. Today, the flexibility of (approximate) confirmation by the jacknife (add simulation, bootstrap and permutation now) makes it relatively easy to ask, for almost any clearly specified exploration, “How far is it confirmed?” <strong>Today, exploratory and confirmatory can–and should–proceed side by side</strong>.</li>
<li>both teacher and student need to realise that many problems do not have a single “right answer”.
<ul>
<li><strong>There can be many ways to approach a body of data. Not all are equally good.</strong> For some bodies of data this may be clear, but for others we may not be able to tell from a single body of data which approach is preferred. Even several bodies of data about very similar situations may not be enough to show which approach should be preferred. Accordingly, it will often be quite reasonable for different analysts to reach somewhat different analyses.</li>
<li>Yet more–to unlock the analysis of a body of day, to find the good way to approach it, may require a key, whose finding is a creative act. <strong>Not everyone can be expected to create the key to any one situation</strong>. And to continue to paraphrase Barnum, no one can be expected to create a key to each situation he or she meets.</li>
<li><strong>To learn about data analysis, it is right that each of us try many things that do not work</strong>–that we tackle more problems than we make expert analyses of. We often learn less from an expertly done analysis than from one where, by not trying something, we missed–at least until we were told about it–an opportunity to learn more. Each teacher needs to recognize this in grading and commenting on problems.</li>
<li>The teacher who heeds these words and admits that there need be <em>no one correct approach</em> may, I regret to contemplate, still want whatever is done to be digit perfect. (Under such a requirement, the write should still be able to pass the course, but it is not clear whether she would get an “A”.) One does, from time to time, have to produce digit-perfect, carefully checked results, but forgiving techniques that are not too distributed by unusual data are also, usually, <em>little disturbed by SMALL arithmetic errors</em>. The techniques we discuss here have been chosen to be forgiving. It is hoped, then, that small arithmetic errors will take little off the problem’s grades, leaving severe penalties for larger errors, either of arithmetic or concept.</li>
</ul></li>
</ul>
<div class="aim">
<p>Everything in Tukey’s EDA book could be done with pencil and paper.</p>
</div>
<p>The sheer joy of working with numbers is one of the delights in reading the book. Here are some of the “scratching down numbers” techniques that we found surprising.</p>
<div id="example-1-stem-and-leaf" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Example 1: Stem-and-leaf<a href="what-is-eda.html#example-1-stem-and-leaf" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A stem-and-leaf plot is a neat way to plot numbers into a histogram type display when only pencil and paper is available. From the display the distribution of the numbers, such as symmetric, skewed, unimodal, multimodal and outliers can be observed. It keeps the digits of the numbers preserved (inexactly, but approximately right) and the numbers are sorted (from lowest to highest or vice verse), so that it is quick to locate the median (middle observation) and different quantiles (eg number with 25% of observations below).</p>
<p>These are the prices of Chevrolet cars listed in the local used car newspaper ads in 1968, as taken from the orange book.</p>
<pre><code>##  [1]  250  150  795  895  695 1699 1499 1099 1693 1166  688 1333  895 1775  895
## [16] 1895  795</code></pre>
<div class="do">
<p>Scratch down these numbers to make a stem-and-leaf plot, one of Tukey’s contributions that can still be seen introductory statistics books.</p>
<!-- 1. Sort the numbers from lowest to highest
2. There are 17 observations, so the 9$^{th}$ is the median. 
3. Break the data into two, keeping the median in both halves. The 5$^{th}$ observation in each will correspond to Q1 and Q3 respectively. 
4. Sketch a vertical axis ranging from the minimum to maximum values, made pretty into whole numbers and nice intervals.
5. Mark the 5 numbers, min, Q1, median, Q3, max, using horizontal lines. 
6. Draw a box by connecting the end points of Q1 to Q3.
7. Draw the whiskers by sketching a vertical line from the middle of the minimum segment to the middle of the Q1 segment, and similarly for the max to Q3.

Then you have a boxplot!-->
<ol style="list-style-type: decimal">
<li>Split the numbers between the 100<span class="math inline">\(^{th}\)</span> and 10<span class="math inline">\(^{th}\)</span> place digits. The left digits form the stem and the right form the leaves of a stem-and-leaf plot. We will also drop the last digit, lose some precision but gain simplicity, making it easier to get an overall sense of the pattern of numbers. Thus 250 becomes 2 5, and 1099 becomes 10 9.</li>
<li>The range of the stem will run from 2 through 18. Write these numbers from smallest to largest vertical, keeping digits in place. Add a vertical line to the right of the numbers.</li>
<li>Now work through the full set of numbers, writing the last digit against it’s corresponding stem.</li>
<li>The last steps is to re-draw it so that the leaves are ordered from lowest (left) to highest on each stem.</li>
<li>And finally, think about the pattern of the numbers in the display. You should see that there are several clumps of numbers in this data.</li>
</ol>
<p><img src="images/stem_and_leaf/6.jpg" /></p>
</div>
<p>Sketching the numbers, checking them off, looking at the result. Hope that was fun!</p>
</div>
<div id="example-1-making-tallies" class="section level3 hasAnchor" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Example 1: Making tallies<a href="what-is-eda.html#example-1-making-tallies" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Most of us have grown up using tally marks to count objects. Tukey provides an alternative way to tally, that he argues is less error prone.</p>
<div class="info">
<p><img src="images/tally_marks.jpg" /></p>
</div>
<p>Instead he advocates for making boxes, with vertices, edges and diagonals, which would do tallying in chunks of 10, with less room for error.</p>
<p>For example, let’s play a car counting game where we count the cars of different colours that go by. Here is a sample of the colours of cars that we see:</p>
<pre><code>##  [1] &quot;white&quot;  &quot;blue&quot;   &quot;red&quot;    &quot;blue&quot;   &quot;red&quot;    &quot;red&quot;    &quot;white&quot;  &quot;yellow&quot;
##  [9] &quot;white&quot;  &quot;white&quot;  &quot;white&quot;  &quot;white&quot;  &quot;white&quot;  &quot;red&quot;    &quot;white&quot;  &quot;blue&quot;  
## [17] &quot;red&quot;    &quot;white&quot;  &quot;blue&quot;   &quot;red&quot;    &quot;white&quot;  &quot;blue&quot;   &quot;blue&quot;   &quot;red&quot;   
## [25] &quot;white&quot;  &quot;red&quot;    &quot;red&quot;    &quot;white&quot;  &quot;white&quot;  &quot;red&quot;</code></pre>
<div class="do">
<ol style="list-style-type: decimal">
<li>Make a square with dots to count observations up to 4</li>
<li>Complete an edge for observations 5-8</li>
<li>Sketch in the diagonals for observations 9, 10.</li>
<li>Repeat the steps for more observations.</li>
</ol>
<p><img src="images/tally_box.jpg" /></p>
</div>
<p>We haven’t seen this way of tallying before which suggests that the idea didn’t catch on. It may be that its more cognitively difficult to switch between points and lines, and mistakes like continuing to draw the box edges to complete the box when only one side should be drawn, might also be made. Nevertheless, the idea of counting this way is neat!</p>
</div>
<div id="example-3-boxplots" class="section level3 hasAnchor" number="2.4.3">
<h3><span class="header-section-number">2.4.3</span> Example 3: Boxplots<a href="what-is-eda.html#example-3-boxplots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Boxplots are based on a reduced numerical summary from the data:</p>
<ul>
<li>Median: the observation that has 50% of the observations above and 50% below.</li>
<li>Hinges, or quartiles (Q1, Q3): the value that has 25% on one side and 75% of observations on the other side.</li>
<li>Inner fences: the observation that is the most extreme, but within 1.5 x the length of the difference between the hinges.</li>
<li>Outer fences: twice that of the inner fence.</li>
</ul>
<p>Below are the maximum temperatures for Melbourne as measured at the airport for January 2016.</p>
<pre><code>##  [1] 28.7 27.5 28.2 24.5 25.6 25.3 23.4 22.8 24.1 32.1 38.3 30.3 43.6 18.0 19.7
## [16] 25.0 32.8 36.5 33.5 31.0 27.5 23.7 22.6 23.7 22.3 29.6 28.9 30.7 19.1 22.8
## [31] 20.6</code></pre>
<div class="do">
<ol style="list-style-type: decimal">
<li>Make a stem-and-leaf of the temperature values. Decide on an appropriate stem size. I recommend using 2<span class="math inline">\(^o\)</span>C for each stem.</li>
<li>Compute the median (will be the 16<span class="math inline">\(^{th}\)</span> observation), the hinges (the 9<span class="math inline">\(^{th}\)</span> observation from each end), the H-spread, and inner fences.</li>
<li>Sketch the resulting boxplot, making sure to mark any outliers as single points.</li>
</ol>
<p><img src="images/melb_temp_boxplot.jpg" /></p>
</div>
</div>
<div id="example-4-easy-re-expression" class="section level3 hasAnchor" number="2.4.4">
<h3><span class="header-section-number">2.4.4</span> Example 4: Easy re-expression<a href="what-is-eda.html#example-4-easy-re-expression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Tukey was a strong advocate of transforming data, especially for visualisation. Today we might focus on transforming data in order to satisfy model constraints such as normally distributed errors. The orange book quotes Tukey:</p>
<blockquote>
<p>We now regard re-expression as a tool, something to let us do a better job of grasping. The grasping is done with the eye and the better job is through a more symmetric appearance.</p>
</blockquote>
<blockquote>
<p>Whatever the data, we can try to gain by straightening or by flattening. When we succeed in doing one or both, we almost always see more clearly what is going on.</p>
</blockquote>
<p>which places the focus on the plots. Examining a single distribution is made easier if the distribution is symmetric. Examining the relationship between two variables is easier of the relationship is straighter, or flattened.</p>
<p>Below is a plot of the population estimate of the USA from 1790 through to 2020. The relationship is far from linear.</p>
<p><img src="eda-book_files/figure-html/uspop-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Tukey would suggest re-expressing <code>y</code> using a log transformation. The base of the log doesn’t so much matter, but a <code>log10</code> will make it easier to reflect the original numbers, because it is powers of 10.</p>
<p>When a response variable is transformed to a log scale, the relationship between <code>x</code> and <code>y</code> can be interpreted as a ratio.</p>
<div class="do">
<ol style="list-style-type: decimal">
<li>In Tukey’s approach to linearising this relationship, the approach would be to
<ol style="list-style-type: lower-alpha">
<li>put the data on a log scale (transform the y variable),</li>
<li>fit a linear model to the top part of the data, after 1900, and</li>
<li>examine the residuals.</li>
</ol></li>
</ol>
</div>
<p><img src="eda-book_files/figure-html/uspop_lin-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Population on a log scale over time is roughly linear after 1900. That means that it follows an exponential growth. The residuals tells a story about world events, that in the decade of the Great Depression, population declined substantially. There is also a hint that in the recent decade that the rate of growth has changed again.</p>
<p>The fitted model 7.92751 + 0.00516<span class="math inline">\(\times\)</span> (year-1900). This would be interpreted as the population increasing geometrically by <span class="math inline">\(10^{0.0516} = 1.126\)</span> each decade, from approximately 85 million in 1900. That means the population would be expected to be about 95 million in 1910, about 153 million by 1950, and go beyond 300 million by 2010.</p>
<p>Similarly, the pattern prior to 1900 is roughly linear on a log scale, which implies an exponential growth, but at a slow rate than after 1900.</p>
<p>A single log scale is not sufficient to linearise the full relationship, but a piece-wise linear fit on the log scale fits the pattern well, at least up to 2020.</p>
</div>
</div>
<div id="exercises" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Exercises<a href="what-is-eda.html#exercises" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li><p>Make a histogram of the total bill, using multiple bin widths. Does it also have a skewed distributions? Is there a similar pattern of multi-modality?</p></li>
<li><p>In the scatterplot of tip vs total bill, why is total on the horizontal axis?</p></li>
<li><p>Make a stem-and-leaf plot of these final exam scores. Is there an easy way to break the scores into distinct clusters?</p></li>
<li><p>Make a stem-and-leaf plot of the monthly average pedestrian counts for Melbourne Central (its a shopping mall and a train station). Compute the median, and the hinges (and H-spread), the inner fences.</p></li>
</ol>
<pre><code>##  [1]  312 1087  768 1024 1329 1328 1206 1065 1432 1447 1438  753 1372 1391 1409
## [16]  177 1240 1295 1250  298 1211 1176 1157  489 1295 1264 1194  260 1302 1305
## [31] 1320  125 1291 1290 1208  159 1287 1701 1237  270 1295 1236 1252  591 1246
## [46] 1164 1225  519</code></pre>
<ol start="5" style="list-style-type: decimal">
<li><p>Turn your numerical summary of the Melbourne pedestrian sensor data into a boxplot. Be sure to mark the observations outside the inner fence as single points to indicate them as outliers.</p></li>
<li><p>Use Tukey’s tallying system to count the number of the different runs (0, 1, 2, 3, 4, 6) for this cricket team’s 10 over innings. A cricket game has 6 balls per over. Why the number of observations a multiple of 6, do you think?</p></li>
</ol>
<pre><code>##  [1] 2 3 0 2 1 1 4 3 0 4 0 0 4 6 0 1 0 0 2 0 2 0 1 2 1 0 0 4 0 0 0 0 4 0 4 0 0 0
## [39] 4 4 1 0 4 1 1 4 2 4 2 2 0 0 0 6 1 0 0 2 1 2 2 2</code></pre>
<ol start="7" style="list-style-type: decimal">
<li>Follow the re-expression example of the US population fitting a linear model to the data prior to 1900. Examine the residuals for drops or booms in the population.</li>
</ol>

</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-bryantsmith1995" class="csl-entry">
Bryant, Peter G., and Marlene A. Smith. 1995. <em>Practical Data Analysis: Case Studies in Business Statistics</em>. chicago: irwin.
</div>
<div id="ref-cookswayne07" class="csl-entry">
Cook, D., and D. Swayne. 2007. <em><span>I</span>nteractive and <span>D</span>ynamic <span>G</span>raphics for <span>D</span>ata <span>A</span>nalysis with Examples Using <span>R</span> and <span>GG</span>obi</em>. New York: Springer.
</div>
<div id="ref-tukey77" class="csl-entry">
Tukey, John. 1977. <em>Exploratory Data Analysis</em>. Reading, MA: Addison-Wesley.
</div>
<div id="ref-tukey1962" class="csl-entry">
Tukey, John W. 1962. <span>“The Future of Data Analysis.”</span> <em>Annals of Mathematical Statistics</em> 33: 1–67.
</div>
<div id="ref-r4ds" class="csl-entry">
Wickham, Hadley, and Garrett Grolemund. 2017. <em>R for Data Science</em>. <a href="https://r4ds.had.co.nz" class="uri">https://r4ds.had.co.nz</a>: O’Reilly.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="initial-data-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["eda-book.pdf", "eda-book.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
